apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: external-dns
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: external-dns
          image: "{{ .Values.externalDns.image.repository }}:{{ .Values.externalDns.image.tag }}"
          imagePullPolicy: {{ .Values.externalDns.image.pullPolicy }}
          args:
            - --source=service
            - --source=ingress
            {{- range .Values.domainFilters }}
            - --domain-filter={{ . }}
            {{- end }}
            - --provider=google
            - --log-format=json
            - --google-zone-visibility=public
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id={{ .Values.externalDns.txtOwnerId }}
            {{- if .Values.dryRun }}
            - --dry-run
            {{- end }}
