apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redb1
  namespace: redis
  labels:
    app: redis-database-1
spec:
  redisEnterpriseCluster:
    name: redis-enterprise-cluster
  proxyPolicy: all-master-shards
  memorySize: 1GB
  databaseSecretName: redis-database-1
  replication: true
  shardCount: 2
  shardsPlacement: sparse
  type: redis
  databasePort: 12000
  persistence: aofEverySecond
  evictionPolicy: noeviction
  modulesList:
    - name: ReJSON
    - name: search
    - name: timeseries
