apiVersion: v1
kind: Namespace
metadata:
  name: java-runner
  labels:
    name: java-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-runner-sa
  namespace: java-runner
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: java-runner-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1001
      max: 1001
readOnlyRootFilesystem: true
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAs
  uid: 1001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 1001
      max: 1001
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-runner-scc-binding
  namespace: java-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:java-runner-scc
subjects:
  - kind: ServiceAccount
    name: java-runner-sa
    namespace: java-runner
