apiVersion: v1
kind: Namespace
metadata:
  name: java-runner
  labels:
    name: java-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-runner-sa
  namespace: java-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-runner
  namespace: java-runner
  labels:
    app: java-runner
    component: java-app-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-runner
  template:
    metadata:
      labels:
        app: java-runner
        component: java-app-runner
    spec:
      restartPolicy: Always
      containers:
      - name: java-runner
        image: ${DOCKER_REGISTRY}/java-runner:latest
        imagePullPolicy: Always
