apiVersion: v1
kind: ConfigMap
metadata:
  name: session-api-config
  namespace: session-api
data:
  REDIS_HOST: REDIS_HOST
  REDIS_PORT: "12000"
  REDIS_DATABASE: "0"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  JAVA_OPTS: "-Xmx512m -Xms256m -Dspring.profiles.active=kubernetes"
  REDIS_CLIENT_TYPE: "jedis"
