apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: session-api
  labels:
    app: redis
type: Opaque
data:
  # Placeholder: replace with Redis database base64 encoded password
  redis-password: Cg==
