apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: session-api
type: Opaque
data:
  redis-password: {{ .Values.redisPassword | b64enc }}
